xlsxFileName = 'articleData.xlsx' ; value only used if not provided on the command line
filesFolderName = 'files' ; value only used if not provided on the command line
defaultUploader = 'admin'
defaultAuthor['givenname'] = 'Editorial Board'
defaultLocale = 'en' ; value only used if not provided on the command line
defaultUserGroupRef['en'] = 'Author'
defaultUserGroupRef['de'] = 'Autor/in'
defaultUserGroupRef['sv'] = 'F&#xF6;rfattare'
; add more defaultUserGroupRefs for your locale as required for your installation
