<?php

return array (
  'articleElementOrder' => 
  array (
    0 => 'id',
    1 => 'submission_file',
    2 => 'publication',
  ),
  'publicationElementOrder' => 
  array (
    0 => 'id',
    1 => 'title',
    2 => 'prefix',
    3 => 'subtitle',
    4 => 'abstract',
    5 => 'coverage',
    6 => 'type',
    7 => 'source',
    8 => 'rights',
    9 => 'licenseUrl',
    10 => 'copyrightHolder',
    11 => 'copyrightYear',
    12 => 'keywords',
    13 => 'agencies',
    14 => 'languages',
    15 => 'disciplines',
    16 => 'subjects',
    17 => 'authors',
    18 => 'article_galley',
    19 => 'citations',
    20 => 'issue_identification',
    21 => 'pages',
    22 => 'covers',
    23 => 'issueId',
  ),
  'authorElementOrder' => 
  array (
    0 => 'givenname',
    1 => 'familyname',
    2 => 'affiliation',
    3 => 'rorAffiliation',
    4 => 'country',
    5 => 'email',
    6 => 'url',
    7 => 'orcid',
    8 => 'biography',
  ),
  'submissionFileElementOrder' => 
  array (
    0 => 'id',
    1 => 'creator',
    2 => 'description',
    3 => 'name',
    4 => 'publisher',
    5 => 'source',
    6 => 'sponsor',
    7 => 'subject',
    8 => 'submission_file_ref',
    9 => 'file',
  ),
  'issueElementOrder' => 
  array (
    0 => 'id',
    1 => 'description',
    2 => 'issue_identification',
    3 => 'date_published',
    4 => 'date_notified',
    5 => 'last_modified',
    6 => 'open_access_date',
    7 => 'sections',
    8 => 'covers',
    9 => 'issue_galleys',
    10 => 'articles',
  ),
  'issueIdentificationElementOrder' => 
  array (
    0 => 'volume',
    1 => 'number',
    2 => 'year',
    3 => 'title',
  ),
  'coverImageElementOrder' => 
  array (
    0 => 'cover_image',
    1 => 'cover_image_alt_text',
    2 => 'embed',
  ),
  'elementsWithLocale' => 
  array (
    0 => 'abbrev',
    1 => 'abstract',
    2 => 'agencies',
    3 => 'article',
    4 => 'article_galley',
    5 => 'biography',
    6 => 'citations',
    7 => 'copyrightHolder',
    8 => 'cover',
    9 => 'coverage',
    10 => 'creator',
    11 => 'description',
    12 => 'disciplines',
    13 => 'familyname',
    14 => 'givenname',
    15 => 'issue_galley',
    16 => 'keywords',
    17 => 'languages',
    18 => 'name',
    19 => 'policy',
    20 => 'prefix',
    21 => 'publisher',
    22 => 'representation',
    23 => 'rights',
    24 => 'source',
    25 => 'sponsor',
    26 => 'subject',
    27 => 'subjects',
    28 => 'submission',
    29 => 'subtitle',
    30 => 'title',
    31 => 'type',
  ),
);
